### DISCUSSION TITLE
可以修改8080端口吗？

### DISCUSSION THREAD

**Discussion by tanglu1323123** [messense/aliyundrive-webdav#594] [Q&A] [answered]
作者您好，请问可以修改8080端口吗？比如docker这两个方法这样修改可以吗？我修改端口试了一下无法打开，8080可以打开。不知道是不支持修改端口 还是我操作错误
```
docker run -d --name=aliyundrive-webdav --restart=unless-stopped -p 8082:8082 \
  -v /etc/aliyundrive-webdav/:/etc/aliyundrive-webdav/ \
  -v /etc/localtime:/etc/localtime \
  -e TZ=Asia/Shanghai \
  -e REFRESH_TOKEN='************' \
  -e WEBDAV_AUTH_USER=admin \
  -e WEBDAV_AUTH_PASSWORD=admin \
  messense/aliyundrive-webdav
```
```
version: '3.3'
services:
  aliyundrive-webdav:
    container_name: aliyundrive-webdav
    restart: unless-stopped
    ports:
      - '8082:8082'
    environment:
      - 'REFRESH_TOKEN=******************'
    image: messense/aliyundrive-webdav
```
