### DISCUSSION TITLE
挂载阿里云盘后只能看见“Parent Directory”

### DISCUSSION THREAD

**Discussion by routescroll** [messense/aliyundrive-webdav#906] [Q&A]
如图所示
使用QNAP的TS-431K
看不到文件和目录，只有一个“Parent Directory”

如下所示手动添加的QNAP的App
```
version: '3.3'
services:
  aliyundrive-webdav:
    container_name: aliyundrive-webdav
    restart: unless-stopped
    ports:
      - '9798:8080'
    environment:
      - 'REFRESH_TOKEN=xxxxxxx'
      - 'WEBDAV_AUTH_USER=admin'
      - 'WEBDAV_AUTH_PASSWORD=admin'
    image: messense/aliyundrive-webdav
```

有哪位朋友知道原因吗？

<img width="560" alt="image" src="https://github.com/messense/aliyundrive-webdav/assets/16577244/1aad3cff-faeb-4f9e-bbe4-06767edc3404">
